# Generated by Django 3.2.8 on 2021-10-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cnpj',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='email',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cpfChefeFamilia',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='integrantefamiliar',
            name='cpf',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cpf',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
