# Generated by Django 3.2.8 on 2021-11-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211021_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='numeroDeDependentes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='familia',
            name='telefone1',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familia',
            name='telefone2',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='integrantefamiliar',
            name='telefone',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
