# Generated by Django 3.2.8 on 2021-11-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211104_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='movimentoitens',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movimentoitens',
            name='id_itens',
        ),
        migrations.AddField(
            model_name='movimentoitens',
            name='descricaoItem',
            field=models.CharField(default=1, max_length=95),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentoitens',
            name='nomeItem',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentoitens',
            name='id_movimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.movimentos'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Itens',
        ),
    ]
