# Generated by Django 3.2.8 on 2021-11-04 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211104_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoitens',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentoitens',
            name='id_movimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movimentos'),
        ),
    ]
