# Generated by Django 3.2.8 on 2021-11-04 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211104_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoitens',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
